### ISSUE TITLE
container-disk-v1alpha base image is not needed/recommended anymore.

### ISSUE THREAD

**Issue by zakkg3** [Tedezed/kubevirt-images-generator#1]
And also cause of python3.7 the yum update its broken.

Now the recommended way is from scratch just add the image. and qcow2 is the recommended one. 

https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html#containerdisk-workflow-example

so something like this should be better:

```
FROM alpine as BUILDER
ARG IMG_URL="https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"

RUN wget $IMG_URL -O ubuntu.qcow2
# ubuntu publish the qcow2 images as .img -.-
FROM scratch
copy  --from=BUILDER /ubuntu.qcow2 /disk/
```

 I am creating the images in this repo: https://github.com/zakkg3/kubevirt-images

but it still needs some automation as you did for this one.

Cheers!

**Comment by alosadagrande** [comment]
@zakkg3 @Tedezed Is it possible to get a kvm/libvirt image from my local hypversion default's pool (/var/lib/libvirt/images) and just containerized the same way you do with original cloud images? or does the cloud images from the major OSes have something special? I have been only successful when containerizing vanilla cloud images...

**Comment by Tedezed** [comment]
@alosadagrande Did you try the following command? `virtctl image-upload`
- https://kubevirt.io/2019/How-To-Import-VM-into-Kubevirt.html

**Comment by alosadagrande** [comment]
Thanks @Tedezed. Actually I am not looking for a persistent VM, I just want to create specific VMs with particular software, upload it to our company registry and allow developers to run the image in the same way as another image.

I was thinking of creating a container image from the KVM VM once modified and push it to the registry.

**Comment by Tedezed** [comment]
@alosadagrande I understand that you mean this. You can use the examples from image guide of Openstack:
- https://docs.openstack.org/image-guide/create-images-manually.html
- https://docs.openstack.org/image-guide/modify-images.html

In the moment you end the custom image, you can upload to your internal registry, you can use the current repo to build de image.
Example:
- Edit file build_variable.
- Comment the next line: https://github.com/Tedezed/kubevirt-images-generator/blob/master/base/Dockerfile#L16
- ADD local image file in Dockerfile

Create your vm using the next volume example:
```
volumes:
  - name: containervolume
    containerDisk:
      image: custom_registry/custom_image:version
```

**Comment by alosadagrande** [comment]
Thank you @Tedezed. Eventually I found useful virt-customize:

```
[root@eko7 images]# virt-customize -v --format qcow2 -a centos8.qcow2 --hostname midgar.city.local --install httpd,mod_ssl --timezone UTC --run-command "systemctl enable httpd" --selinux-relabel --upload index.html:/var/www/html/index.html
``` 

And a new builder tool based on composer-cli and lorax. There is a nice blog post in Red Hat's developer blog: https://developers.redhat.com/blog/2019/05/08/red-hat-enterprise-linux-8-image-builder-building-custom-system-images/

**Comment by Tedezed** [comment]
First thanks for taking the trouble! @zakkg3
- it seems that everything works fine version `0.13.7`, yum update worked.
- I will continue to use the image `kubevirt/container-disk-v1alpha` for backward compatibility although I will consider it for the future.

> Users can inject a VirtualMachineInstance disk into a container image in a way that is consumable by the KubeVirt runtime. Disks must be placed into the /disk directory inside the container. Raw and qcow2 formats are supported. Qcow2 is recommended in order to reduce the container image’s size.  Containerdisks can and should be based on scratch. No content except the image is required.

> Note: Prior to kubevirt 0.20, the containerDisk image needed to have kubevirt/container-disk-v1alpha as base image.

Cheers! :+1:
