### ISSUE TITLE
Ubuntu jammy-jellyfish is the LTS for 2022, not Kinetic Kudu

### ISSUE THREAD

**Issue by addyess** [Tedezed/kubevirt-images-generator#3]
I happened upon your images via this [blog](https://josebiro.medium.com/getting-kubevirt-and-k0s-to-play-nicely-on-ubuntu-20-04-lts-39c33f18a8b2) and saw that when i loaded 22.0 -- i was presented with Kinetic Kudu.

Could your build_variables point at a different server image?

**Comment by Tedezed** [comment]
Merged, thanks for the contribution
Sorry for the delay, you missed the notification

**Comment by Tedezed** [comment]
Updated, I close the issue ✅
